# .github/workflows/deploy.yml
name: Deploy Backend

on:
  # push:
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone le repo
        uses: actions/checkout@v3

      - name: Login Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: monRegistry.azurecr.io
          username: ${{ SECRET.USERNAME }}
          password: ${{ SECRET.MOTDEPASSE }}

      - name: Build & Push
        run: |
          docker build -f backend/Dockerfile ./backend \
            -t monRegistry.azurecr.io/backend:latest
          docker push monRegistry.azurecr.io/backend:latest

      - name: Deploy sur Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name TP2_objet_connecte \
              --resource-group monRG \
              --image monRegistry.azurecr.io/backend:latest
